### ISSUE TITLE
ModuleManager error when patching RealChute

### ISSUE THREAD

**Issue by bHXDgiuMa5yLHyC8** [linuxgurugamer/InlineBallutes#2]
MM gave me these errors when attempting to use Inline Ballutes 1.2.9.3 with Real Chute 1.4.6 in KSP 1.4.3

```
[ERR 02:42:30.610] [ModuleManager] Error - Cannot parse variable search when inserting new key caseMass = #$/../mass$

[LOG 02:42:30.610] [ModuleManager] Applying update KermangeddonIndustries/InlineBallutes/Patches/RealChute/@PART[InlineBallute125] to KermangeddonIndustries/InlineBallutes/Ballute125/PART
[ERR 02:42:30.610] [ModuleManager] Error - Cannot parse variable search when inserting new key caseMass = #$/../mass$

[LOG 02:42:30.611] [ModuleManager] Applying update KermangeddonIndustries/InlineBallutes/Patches/RealChute/@PART[InlineBallute250] to KermangeddonIndustries/InlineBallutes/Ballute250/PART
[ERR 02:42:30.611] [ModuleManager] Error - Cannot parse variable search when inserting new key caseMass = #$/../mass$

[LOG 02:42:30.644] [ModuleManager] Applying update KermangeddonIndustries/InlineBallutes/Patches/RealChute/@PART[InlineBallute375] to KermangeddonIndustries/InlineBallutes/Ballute375/PART
[ERR 02:42:30.645] [ModuleManager] Error - Cannot parse variable search when inserting new key caseMass = #$/../mass$

[LOG 02:42:30.645] [ModuleManager] Applying update KermangeddonIndustries/InlineBallutes/Patches/RealChute/@PART[InlineBallute500] to KermangeddonIndustries/InlineBallutes/Ballute500/PART
[ERR 02:42:30.645] [ModuleManager] Error - Cannot parse variable search when inserting new key caseMass = #$/../mass$
```

**Comment by bHXDgiuMa5yLHyC8** [comment]
I fixed this error with the method suggested here: https://forum.kerbalspaceprogram.com/index.php?/topic/50533-141-module-manager-307-may-5th-2018-its-dangerous-to-go-alone-take-those-cats-with-you/&do=findComment&comment=3254080

**Comment by linuxgurugamer** [comment]
Would be nice if you could either do a PR, or at least paste the file into the comments here

**Comment by bHXDgiuMa5yLHyC8** [comment]
I'm still having problems; Inline Ballutes is not functioning with Real Chute at all. In the VAB, they don't show up with the other parachutes in the menu, right clicking them only gives the next/previous size options which do nothing, they don't show up in the staging sequence, and right-clicking them on the pad doesn't even bring up a window.

**Comment by linuxgurugamer** [comment]
ok, I'll have to look at it, but if you were still having problems, would have been nice to update the ticket

**Comment by linuxgurugamer** [comment]
My testing is not showing the problem you are displaying.  
Do you have FAR installed?
Please upload a complete log file for me to look at

**Comment by linuxgurugamer** [comment]
Ok, I see the problem, but you really should have uploaded your complete log file, it was related to FAR being there, which I don't play with.
