### ISSUE TITLE
MiniAVC.dll can be removed

### ISSUE THREAD

**Issue by Gordon-Dry** [linuxgurugamer/InlineBallutes#8]
Just a reminder.

**Comment by jbayer-a3k** [comment]
Well, that's why I have ZeroMiniAVC set as a requirement when installing via CKAN.
When I next release this, it will be gone

**Comment by linuxgurugamer** [comment]
Well, yes, that's why I have ZeroMiniAVc set as a requirement.  

Just noticed that there is a good PR waiting, so I'll be doing a new release which will have it removed

**Comment by Gordon-Dry** [comment]
> ZeroMiniAVc

Not mentioned anywhere in the mod description - and this is the only mod in my setup that still contains (aka. contained)  it.

**Comment by linuxgurugamer** [comment]
I just did a release, should be gone.  And I can't update every mod everytime there is a change.  That's why I strongly recommend using CKAN, it takes care of things like this automatically.
